services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./create.sql:/tmp/create.sql
    restart: unless-stopped
volumes:
  pg-data: